name: Release packages
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - name: Publish to npm
        run: npm publish workspace=packages/ui/react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}